CREATE TABLE IF NOT EXISTS "#__wf_profiles" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(255) NOT NULL,
    "description" text NOT NULL,
    "users" text NOT NULL,
    "types" text NOT NULL,
    "components" text NOT NULL,
    "area" smallint NOT NULL,
    "device" varchar(255) NOT NULL,
    "rows" text NOT NULL,
    "plugins" text NOT NULL,
    "published" smallint NOT NULL,
    "ordering" integer NOT NULL,
    "checked_out" integer,
    "checked_out_time" timestamp without time zone,
    "params" text NOT NULL
);